channels:
- pytorch
- menpo
- conda-forge
- anaconda
- defaults
dependencies:
- _libgcc_mutex=0.1
- _sysroot_linux-64_curr_repodata_hack=3
- argon2-cffi=20.1.0
- async_generator=1.10
- attrs=20.3.0
- backcall=0.2.0
- binutils_impl_linux-64=2.31.1
- binutils_linux-64=2.31.1
- blas=1.0
- bleach=3.3.0
- brotlipy=0.7.0
- ca-certificates=2020.12.5
- certifi=2020.12.5
- cffi=1.14.4
- chardet=4.0.0
- cryptography=3.3.1
- cudatoolkit=11.0.221
- cycler=0.10.0
- dbus=1.13.18
- decorator=4.4.2
- defusedxml=0.6.0
- entrypoints=0.3
- expat=2.2.10
- fontconfig=2.13.1
- freetype=2.10.4
- gcc_impl_linux-64=7.3.0
- gcc_linux-64=7.3.0
- glew=2.1.0
- glfw3=3.2.1
- glib=2.66.1
- gst-plugins-base=1.14.0
- gstreamer=1.14.0
- gxx_impl_linux-64=7.3.0
- gxx_linux-64=7.3.0
- icu=58.2
- idna=2.10
- importlib_metadata=2.0.0
- intel-openmp=2020.2
- ipykernel=5.3.4
- ipython=7.20.0
- ipython_genutils=0.2.0
- jedi=0.17.0
- jinja2=2.11.3
- joblib=1.0.1
- jpeg=9b
- json5=0.9.5
- jsonschema=3.2.0
- jupyter_client=6.1.7
- jupyter_core=4.7.1
- jupyterlab=2.2.6
- jupyterlab_pygments=0.1.2
- jupyterlab_server=1.2.0
- kernel-headers_linux-64=3.10.0
- kernel-headers_linux-ppc64le=3.10.0
- kiwisolver=1.3.1
- lcms2=2.11
- ld_impl_linux-64=2.33.1
- libblas=3.8.0
- libcblas=3.8.0
- libdrm-cos6-x86_64=2.4.65
- libdrm-cos7-ppc64le=2.4.97
- libdrm-cos7-x86_64=2.4.97
- libedit=3.1.20191231
- libffi=3.3
- libgcc-ng=9.1.0
- libgfortran-ng=7.3.0
- libglu=9.0.0
- libglvnd-cos7-ppc64le=1.0.1
- libglvnd-cos7-x86_64=1.0.1
- libglvnd-glx-cos7-ppc64le=1.0.1
- libglvnd-glx-cos7-x86_64=1.0.1
- libpng=1.6.37
- libsodium=1.0.18
- libstdcxx-ng=9.1.0
- libtiff=4.1.0
- libuuid=1.0.3
- libuv=1.40.0
- libx11-common-cos6-x86_64=1.6.4
- libx11-cos6-x86_64=1.6.4
- libxcb=1.14
- libxml2=2.9.10
- lz4-c=1.9.3
- markupsafe=1.1.1
- matplotlib=3.3.2
- matplotlib-base=3.3.2
- mesa-khr-devel-cos7-ppc64le=18.3.4
- mesa-khr-devel-cos7-x86_64=18.3.4
- mesa-libgl-cos6-x86_64=11.0.7
- mesa-libgl-cos7-ppc64le=18.3.4
- mesa-libgl-cos7-x86_64=18.3.4
- mesa-libgl-devel-cos6-x86_64=11.0.7
- mesa-libgl-devel-cos7-ppc64le=18.3.4
- mesa-libgl-devel-cos7-x86_64=18.3.4
- mesa-libglapi-cos7-ppc64le=18.3.4
- mesa-libglapi-cos7-x86_64=18.3.4
- mesalib=18.3.1
- mistune=0.8.4
- mkl=2020.2
- mkl-service=2.3.0
- mkl_fft=1.2.0
- mkl_random=1.1.1
- nbclient=0.5.1
- nbconvert=6.0.7
- nbformat=5.1.2
- ncurses=6.2
- nest-asyncio=1.4.3
- ninja=1.10.2
- notebook=6.2.0
- olefile=0.46
- openssl=1.1.1j
- osmesa=12.2.2.dev
- pandas=1.1.5
- pandoc=2.11
- pandocfilters=1.4.3
- parso=0.8.1
- patchelf=0.12
- pcre=8.44
- pexpect=4.8.0
- pickleshare=0.7.5
- prometheus_client=0.9.0
- prompt-toolkit=3.0.8
- ptyprocess=0.7.0
- pycparser=2.20
- pygments=2.7.4
- pyopenssl=20.0.1
- pyparsing=2.4.7
- pyqt=5.9.2
- pyrsistent=0.17.3
- pysocks=1.7.1
- python=3.8.5
- python-dateutil=2.8.1
- python_abi=3.8
- pytorch=1.7.1
- pytz=2021.1
- pyzmq=20.0.0
- qt=5.9.7
- readline=8.1
- requests=2.25.1
- scikit-learn=0.23.2
- scipy=1.6.0
- seaborn=0.11.1
- send2trash=1.5.0
- sip=4.19.13
- six=1.15.0
- sqlite=3.33.0
- sysroot_linux-64=2.17
- sysroot_linux-ppc64le=2.17
- terminado=0.9.2
- testpath=0.4.4
- threadpoolctl=2.1.0
- tk=8.6.10
- torchvision=0.8.2
- tornado=6.1
- traitlets=5.0.5
- urllib3=1.26.3
- wcwidth=0.2.5
- webencodings=0.5.1
- wheel=0.36.2
- xorg-fixesproto=5.0
- xorg-kbproto=1.0.7
- xorg-libx11=1.6.12
- xorg-libxcursor=1.2.0
- xorg-libxext=1.3.4
- xorg-libxfixes=5.0.3
- xorg-libxinerama=1.1.4
- xorg-libxrandr=1.5.2
- xorg-libxrender=0.9.10
- xorg-randrproto=1.5.0
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xz=5.2.5
- zeromq=4.3.3
- zipp=3.4.0
- zlib=1.2.11
- zstd=1.4.5
- pip:
  - absl-py==0.11.0
  - ale-py==0.7.4
  - astunparse==1.6.3
  - autorom==0.4.2
  - autorom-accept-rom-license==0.4.2
  - black==21.9b0
  - box2d==2.3.10
  - cachetools==4.2.1
  - click==7.1.2
  - cloudpickle==1.6.0
  - cocos2d==0.6.5
  - cython==0.29.21
  - data==0.4
  - deepdish==0.3.6
  - dm-control==0.0.425341097
  - dm-env==1.5
  - dm-tree==0.1.6
  - docopt==0.6.2
  - fasteners==0.16
  - filelock==3.0.12
  - flatbuffers==1.12
  - funcsigs==1.0.2
  - future==0.18.2
  - future-fstrings==1.2.0
  - gast==0.3.3
  - glfw==2.0.0
  - google-auth==1.26.0
  - google-auth-oauthlib==0.4.2
  - google-pasta==0.2.0
  - grpcio==1.32.0
  - gym==0.21.0
  - h5py==2.10.0
  - huggingface-hub==0.0.8
  - imageio==2.9.0
  - imageio-ffmpeg==0.4.3
  - importlib-metadata==4.11.2
  - importlib-resources==5.4.0
  - ipdb==0.13.4
  - jsonpickle==0.9.6
  - keras==2.8.0
  - keras-nightly==2.5.0.dev2021032900
  - keras-preprocessing==1.1.2
  - labmaze==1.0.3
  - libclang==13.0.0
  - lockfile==0.12.2
  - lxml==4.6.2
  - markdown==3.3.3
  - mujoco-py==2.1.2.14
  - munch==2.5.0
  - mypy-extensions==0.4.3
  - networkx==2.5
  - numexpr==2.7.3
  - numpy==1.20.1
  - oauthlib==3.1.0
  - opencv-python==4.5.1.48
  - opt-einsum==3.3.0
  - ordered-set==4.1.0
  - packaging==21.3
  - pathspec==0.9.0
  - patsy==0.5.2
  - pillow==7.2.0
  - pip==22.0.4
  - platformdirs==2.4.0
  - pot==0.8.1.0
  - protobuf==3.19.4
  - psutil==5.8.0
  - py-cpuinfo==8.0.0
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pybullet==3.1.0
  - pycolab==1.2
  - pyglet==1.5.0
  - pylatex==1.4.1
  - pyopengl==3.1.5
  - pywavelets==1.1.1
  - regex==2021.4.4
  - requests-oauthlib==1.3.0
  - rsa==4.7
  - ruamel-yaml==0.16.12
  - ruamel-yaml-clib==0.2.2
  - sacred==0.7.4
  - sacremoses==0.0.45
  - scikit-image==0.18.1
  - setuptools==60.10.0
  - shutilwhich==1.1.0
  - statsmodels==0.13.2
  - tables==3.6.1
  - tabulate==0.8.9
  - tempdir==0.7.1
  - tensorboard==2.8.0
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.0
  - tensorboardx==1.8
  - tensorflow==2.8.0
  - tensorflow-io-gcs-filesystem==0.24.0
  - termcolor==1.1.0
  - tf-estimator-nightly==2.8.0.dev2021122109
  - tifffile==2021.2.26
  - tokenize-rt==4.2.1
  - tokenizers==0.10.2
  - tomli==1.2.1
  - torch-tb-profiler==0.2.1
  - tqdm==4.59.0
  - typing-extensions==4.1.1
  - werkzeug==1.0.1
  - wrapt==1.12.1
name: pomdp
prefix: /home/mila/t/tianwei.ni/.conda/envs/pomdp
