seed: 1
cuda: -1 # use_gpu
env:
  env_type: meta
  env_name: HalfCheetahVel-v0
  max_rollouts_per_task: 2 # k=2, H=200, H^+ =400

  num_tasks: 120
  num_train_tasks: 100
  num_eval_tasks: 20

train:
  # sample complexity: BAMDP horizon * (num_init_rollouts_pool * num_train_tasks
    #  + num_iters * num_tasks_sample * num_rollouts_per_iter)
    # 0.5k iters -> 5M steps
  # original rl training steps: num_iters * updates_per_iter = 1M
    # now makes it same as env steps
  num_iters: 500 # 38000 # number meta-training iterates
  num_init_rollouts_pool: 500 # before training
  num_rollouts_per_iter: 25  #
  buffer_size: 1e6

  num_updates_per_iter: 200 # equal, or positive integer, e.g. 20, 200, 1000
  batch_size: 32 # to tune based on sampled_seq_len

eval:
  log_interval: 4 # 10 num of iters
  save_interval: 100 # -1
  log_tensorboard: false

policy:
  arch: mlp
  algo: sac # [td3, sac]

  dqn_layers: [128, 128, 128]
  policy_layers: [128, 128, 128]
  lr: 0.0003
  gamma: 0.99
  tau: 0.005

  # sac alpha
  entropy_alpha: 0.2 # tend to be det policy...
  automatic_entropy_tuning: true
  alpha_lr: 0.0003
